version: "3.1"

# todo check env var of wordpresss containing a path

services:
  mariadb:
    container_name: mariadb
    build:
      context: "./requirements/mariadb"
      args:
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
        - DB_NAME=${DB_NAME}
        - DB_USER=${DB_USER}
        - DB_USER_HOST=${DB_USER_HOST}
        - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - type: volume
        source: db
        target: /var/lib/mysql
    networks:
      - network
    restart: always

  wordpress:
    container_name: wordpress
    environment:
      - WP_URL=${WP_URL}
      - WP_TITLE=${WP_TITLE}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_USER=${WP_USER}
      - WP_USER_EMAIL=${WP_USER_EMAIL}
      - WP_USER_PASSWORD=${WP_USER_PASSWORD}
    build:
      context: "./requirements/wordpress"
      args:
        - WP_DB_HOST=${DB_HOST}
        - WP_DB_NAME=${DB_NAME}
        - WP_DB_USER=${DB_USER}
        - WP_DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      - mariadb
    volumes:
      - type: volume
        source: wordpress
        target: /usr/share/wordpress
    networks:
      - network
    restart: always

  nginx:
    container_name: nginx
    build: "./requirements/nginx"
    ports:
      - "443:443"
    depends_on:
      - wordpress
    volumes:
      - type: volume
        source: wordpress
        target: /usr/share/wordpress
    networks:
      - network
    restart: always

  ftp:
    container_name: ftp
    build:
      context: "./requirements/ftp"
      args:
        - FTP_USER=${FTP_USER}
        - FTP_PASSWORD=${FTP_PASSWORD}
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    depends_on:
      - wordpress
    volumes:
      - type: volume
        source: wordpress
        target: /var/ftp
    networks:
      - network
    restart: always

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      device: /home/ngonzale/data/db
      o: bind
  wordpress:
    driver: local
    driver_opts:
      type: none
      device: /home/ngonzale/data/wordpress
      o: bind

networks:
  network:
